######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 22 13:44:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= app_bundle
QT += network

# Input
HEADERS += QtCallback.h test.h
SOURCES += QtCallback.cpp test.cpp
